-- AlterTable
ALTER TABLE "rms_projects" ADD COLUMN     "currency" TEXT,
ADD COLUMN     "deal_tech_stack" TEXT,
ADD COLUMN     "deal_type" TEXT,
ADD COLUMN     "description" TEXT,
ADD COLUMN     "documents_folder" TEXT,
ADD COLUMN     "exchange_rate" DOUBLE PRECISION,
ADD COLUMN     "expected_revenue_cents" INTEGER,
ADD COLUMN     "lead_source" TEXT,
ADD COLUMN     "probability" INTEGER,
ADD COLUMN     "product" TEXT,
ADD COLUMN     "resource_alignment_required" TEXT,
ADD COLUMN     "sub_practice_1_amount_cents" INTEGER,
ADD COLUMN     "sub_practice_1_name" TEXT,
ADD COLUMN     "sub_practice_2_amount_cents" INTEGER,
ADD COLUMN     "sub_practice_2_name" TEXT,
ADD COLUMN     "sub_practice_3_amount_cents" INTEGER,
ADD COLUMN     "sub_practice_3_name" TEXT,
ADD COLUMN     "sub_practice_4_amount_cents" INTEGER,
ADD COLUMN     "sub_practice_4_name" TEXT,
ADD COLUMN     "total_deal_amount_cents" INTEGER;
